# Generated by Django 3.1.4 on 2021-01-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Response Message',
                'verbose_name_plural': 'Response Messages',
                'ordering': ('-time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('picture', models.ImageField(upload_to='panel/members')),
                ('social_link', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('post_type', models.SmallIntegerField(choices=[(1, 'Moderator'), (2, 'Administrator'), (3, 'Co-Administrator'), (4, 'General Secretary'), (5, 'Assistant Secretary'), (6, 'Sector Lead'), (6, 'Sector Co Lead')])),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.panelpost')),
            ],
            options={
                'ordering': ('-year_start', 'post_type'),
            },
        ),
        migrations.CreateModel(
            name='PageParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=220, unique=True)),
                ('heading', models.TextField()),
                ('paragraph', models.TextField()),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.portfoliopage')),
            ],
        ),
    ]
