# Generated by Django 3.1.4 on 2021-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemessage',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
