# Generated by Django 3.1.4 on 2021-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210107_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelmember',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
